apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: blog
    spec:
      containers:
      - image: mayankt/blog:master
        name: blog
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: blog
  name: blog
spec:
  ports:
  - name: "blogsite"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: blog
  type: LoadBalancer
status:
  loadBalancer: {}