# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tech Blog
description: Get your nerd on.
subtitle: DevOps, Cloud, and Emerging Technology
author: Mayank Tahilramani
language: en
timezone: America/Los_Angeles
read_speed: 180

# URL
## If your site is put in a subdirectory, set url as 'http://blog.tahil.site/child' and root as '/child/'
url: http://blog.tahil.site
root: /
permalink: :title/
permalink_defaults:

# Incorporate markdown files https://github.com/tea3/hexo-include-markdown
include_markdown:
  dir: source/_template   # Base directory of template markdown
  verbose: true          # If you want to check the path of markdown that use <!-- md --> tag , please set the true.

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# This plugin will inject a TOC only when a placeholder(<!-- toc -->) found in the raw markdown files. And the TOC will be injected after the placeholder. https://github.com/bubkoo/hexo-toc
toc:
  maxdepth: 3
  class: toc
  # slugify: transliteration
  decodeEntities: true
  anchor:
    position: before
    symbol: ''
    style: header-anchor

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
# markdown:
#   render:
#     html: true

# Github Emoji support: https://github.com/crimx/hexo-filter-github-emojis
githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  styles:
  localEmojis:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# This is a Hexo tag plugin for including a tweetable quote into your pages/posts with link to post. EX: {% tweetableQuote 'I am a deeply superficial person.' 'Andy Warhol' 'quote,qod' %}
tweetableQuote:
  quote_font_color: #258fb8
  quote_font_size: 1.7em
  link_font_color: #6e7b8d
  link_font_size: 1.0em
  via_twitter_account: mayanktahil

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM-DD-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hiker


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 4
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

# Generates site map
sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
